name:                morse
version:             0.1.0.0
github:              "KhuongLe329/morse_haskell"
license:             BSD3
author:              "Le Manh Khuong"
maintainer:          "lemanhkhuong2611@gmail.com"
copyright:           "2021 Le Manh Khuong"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/KhuongLe329/morse_haskell#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- QuickCheck

library:
  source-dirs: src

executables:
  morse-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - morse

tests:
  morse-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - morse
